import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';import './style.css';
function Icon({name}){const paths={Overview:<><path d="m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9"/></>,Products:<><path d="m12 3 9 5v9l-9 5-9-5V8zM3 8l9 5 9-5M12 13v9M7 5l10 6"/></>,Queue:<><path d="M8 5h13M8 12h13M8 19h13"/><circle cx="3" cy="5" r="1"/><circle cx="3" cy="12" r="1"/><circle cx="3" cy="19" r="1"/></>,Refresh:<><path d="M20 7A9 9 0 1 0 21 15M20 3v5h-5"/></>};return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function App(){const[data,setData]=useState(null),[auth,setAuth]=useState(false),[code,setCode]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false);
async function refresh(){setBusy(true);try{const r=await fetch('/api/data');if(r.status===401){setAuth(false);return}const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setAuth(true);setError('')}catch(e){setError(e.message)}finally{setBusy(false)}}
useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[]);
async function logout(){await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setAuth(false);setData(null);setError('')}
async function login(e){e.preventDefault();setBusy(true);try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:code})});if(!r.ok)throw Error('Incorrect access code');setCode('');await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
if(!auth)return <div className="login"><div className="brand">Print <span>desk</span></div><h1>Welcome back</h1><p>Enter your access code to view printers and label activity.</p><form onSubmit={login}><label htmlFor="code">Access code</label><input id="code" autoComplete="current-password" type="password" value={code} onChange={e=>setCode(e.target.value)} required/><button disabled={busy}>{busy?'Connecting…':'Open dashboard'}</button></form>{error&&<p role="alert" className="error">{error}</p>}</div>;
const printers=data?.printers||[],jobs=data?.jobs||[],products=data?.products||[];const online=p=>p.last_heartbeat&&Date.now()-Date.parse(p.last_heartbeat)<90000;const title={Overview:'Printer overview',Products:'Product catalog',Queue:'Print queue'}[tab];
const queueMessage = !data?.windowsQueueConnected ? 'Waiting for the Windows agent to report its queue. Install agent 2.2 or later.' : !data?.windowsQueueFresh ? 'Windows queue report is stale. Showing the last known status.' : 'Windows queue reporting connected. Submitted means accepted by DYMO; physical output is not independently confirmed.';
function Jobs(){return <div className="table-wrap"><table><thead><tr>{['SKU','Product','Printer','Status','Email received'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{jobs.length?jobs.map(j=><tr key={j.id}><td className="mono">{j.sku}</td><td dir="auto">{j.product_name}</td><td>{printers.find(p=>p.id===j.printer_id)?.name||'Unassigned'}</td><td>{j.status==='submitted'?'Submitted to DYMO':j.status}<small>{j.source}{j.report_stale?' · stale report':''}</small>{j.error&&<small className="red">{j.error}</small>}</td><td>{new Date(j.created_at).toLocaleString()}</td></tr>):<tr><td colSpan="5" className="empty">{data?.windowsQueueConnected?'No reported jobs':'No queue report received'}<small>{queueMessage}</small></td></tr>}</tbody></table></div>}
return <><aside><div className="brand">Print <span>desk</span></div><nav>{['Overview','Products','Queue'].map(x=><button key={x} className={tab===x?'selected':''} onClick={()=>{setTab(x);setQuery('')}}><Icon name={x}/>{x}</button>)}</nav><button className="logout" onClick={logout}>Log out</button></aside><main><header><div><h1>{title}</h1><p>{tab==='Overview'?'Connections, heartbeats and label activity':tab==='Products'?'Active products synced from SUMIT':'Up to 200 reported jobs per Windows agent, plus cloud jobs'}</p></div><button onClick={refresh} disabled={busy}><Icon name="Refresh"/>{busy?'Refreshing…':'Refresh'}</button></header>{error&&<div role="alert" className="error banner">{error} Showing last successful update.</div>}
{tab==='Overview'&&<><div className="metrics">{[['Active products',products.length],['Agents online',printers.filter(online).length],['Pending labels',data?.windowsQueueConnected?(data?.queueCounts?.pending||0)+(data?.queueCounts?.queued||0):'—'],['Needs attention',printers.filter(p=>!online(p)||p.status==='printer_offline'||p.status==='printer_unreachable'||p.status==='queue_paused').length]].map(([label,n])=><div key={label}><span>{label}</span><strong className={label==='Needs attention'&&n?'red':''}>{n}</strong></div>)}</div><section><h2>Printers</h2><div className="table-wrap"><table><thead><tr>{['Windows','Agent','Printer','Mode','Last seen'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{printers.map(p=><tr key={p.id}><td><b>{p.name}</b>{p.machine_name&&<small>{p.machine_name}</small>}</td><td><span className={online(p)?'online':''}>{online(p)?'Online':p.last_heartbeat?'Offline':'Awaiting heartbeat'}</span></td><td>{p.status==='printer_unreachable'?'Service unreachable':p.status==='printer_offline'?'Disconnected':p.telemetry?.devices?.some(d=>d.connected&&d.name===p.device_name)?(online(p)?'Connected':'Connected (last report)'):'Not reported'}{p.last_error&&<small className="red">{p.last_error}</small>}</td><td>{p.telemetry?.mode||'Not reported'}</td><td>{p.last_heartbeat?new Date(p.last_heartbeat).toLocaleString():'Never'}</td></tr>)}{!printers.length&&<tr><td colSpan="5">No registered printers</td></tr>}</tbody></table></div><div className="banner">{queueMessage}</div></section><section><h2>Reported print jobs</h2><Jobs/></section></>}
{tab==='Products'&&<section><label className="search-label" htmlFor="search">Search {products.length} products</label><input id="search" type="search" placeholder="SKU or product name" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Last synced</th></tr></thead><tbody>{products.filter(p=>(p.sku+' '+p.name).toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.sku}><td className="mono">{p.sku}</td><td dir="auto">{p.name}</td><td>{new Date(p.synced_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}
{tab==='Queue'&&<section><div className="banner">{queueMessage}</div>{data?.windowsQueueConnected&&<p>Pending: {(data?.queueCounts?.pending||0)+(data?.queueCounts?.queued||0)} · Submitted: {data?.queueCounts?.submitted||0} · Uncertain: {data?.queueCounts?.uncertain||0} · Blocked emails: {data?.blockedEmailCount||0}</p>}<Jobs/>{data?.blockedEmails?.length>0&&<><h2>Blocked emails</h2>{data.blockedEmails.map(e=><p className="error" key={e.printer_id+e.id}>{new Date(e.created_at).toLocaleString()}: {e.error}</p>)}</>}</section>}<footer>Updates every 15 seconds. Last update: {data&&new Date(data.now).toLocaleTimeString()}</footer></main></>}
createRoot(document.getElementById('root')).render(<App/>);
